// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'App': string;
  'App-logo-spin': string;
  'AppHeader': string;
  'AppLink': string;
  'AppLogo': string;
  'AppLogoSpin': string;
}
export const cssExports: CssExports;
export default cssExports;
